### ISSUE TITLE
KeyError: 'parent' while exporting discussion comments

### ISSUE THREAD

**Issue by zopyx** [collective/collective.exportimport#112]
Plone 4.3.20 (AT) with current checkout from master generates these errors for discussion items:

```
2022-04-12T16:07:55 ERROR collective.exportimport.export_content Error exporting http://dev2.zopyx.de:5080/eteaching/community/communityevents/ringvorlesung/hybride-lehrszenarien-gestalten/++conversation++default/1602677734552386
Traceback (most recent call last):
  File "/home/ajung/sandboxes/iwm/plone4.buildout/src/collective.exportimport/src/collective/exportimport/export_content.py", line 284, in export_content
    item = self.fix_url(item, obj)
  File "/home/ajung/sandboxes/iwm/plone4.buildout/src/collective.exportimport/src/collective/exportimport/export_content.py", line 428, in fix_url
    if item["parent"]["@id"] != parent_url:
KeyError: 'parent'
```

**Comment by petschki** [comment]
Just got the same here on Plone 4.3.20/AT with about 200 Commented Items and can confirm, that unchecking "Comments" in the export form and using `@@export_discussion` instead fixes this issue.
