### ISSUE TITLE
Plone 6 tests fail with Python 3.10

### ISSUE THREAD

**Issue by pbauer** [collective/collective.exportimport#150]
I disabled testing 3.10 in 291690a6121c23a02e1e61ea4ac1eb8c378b2509
Anyone knows what that issue (https://github.com/collective/collective.exportimport/actions/runs/3189139268/jobs/5202608840#step:9:652) is:

```
plone60-py310 run-test: commands[0] | /home/runner/work/collective.exportimport/collective.exportimport/.tox/plone60-py310/bin/test
Traceback (most recent call last):
  File "/home/runner/work/collective.exportimport/collective.exportimport/.tox/plone60-py310/bin/test", line 291, in <module>
    sys.exit(zope.testrunner.run((['-s', 'collective.exportimport', '--auto-color', '--auto-progress']) + [
  File "/home/runner/eggs/zope.testrunner-5.5-py3.10.egg/zope/testrunner/__init__.py", line 31, in run
    failed = run_internal(defaults, args, script_parts=script_parts, cwd=cwd,
  File "/home/runner/eggs/zope.testrunner-5.5-py3.10.egg/zope/testrunner/__init__.py", line 52, in run_internal
    from zope.testrunner.runner import Runner
  File "/home/runner/eggs/zope.testrunner-5.5-py3.10.egg/zope/testrunner/runner.py", line 41, in <module>
    from zope.testrunner.options import get_options
  File "/home/runner/eggs/zope.testrunner-5.5-py3.10.egg/zope/testrunner/options.py", line 32, in <module>
    from zope.testrunner.profiling import available_profilers
  File "/home/runner/eggs/zope.testrunner-5.5-py3.10.egg/zope/testrunner/profiling.py", line 19, in <module>
    import pstats
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/pstats.py", line 58, in <module>
    class FunctionProfile:
  File "/home/runner/eggs/dataclasses-0.6-py3.10.egg/dataclasses.py", line 950, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/home/runner/eggs/dataclasses-0.6-py3.10.egg/dataclasses.py", line 800, in _process_class
    cls_fields = [_get_field(cls, name, type)
  File "/home/runner/eggs/dataclasses-0.6-py3.10.egg/dataclasses.py", line 800, in <listcomp>
    cls_fields = [_get_field(cls, name, type)
  File "/home/runner/eggs/dataclasses-0.6-py3.10.egg/dataclasses.py", line 659, in _get_field
    if (_is_classvar(a_type, typing)
  File "/home/runner/eggs/dataclasses-0.6-py3.10.egg/dataclasses.py", line 550, in _is_classvar
    return type(a_type) is typing._ClassVar
AttributeError: module 'typing' has no attribute '_ClassVar'. Did you mean: 'ClassVar'?
ERROR: InvocationError for command /home/runner/work/collective.exportimport/collective.exportimport/.tox/plone60-py310/bin/test (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   plone60-py310: commands failed
```

**Comment by pbauer** [comment]
Locally it works with `tox -e plone60-py310`, so maybe something in `.github/workflows/tests.yml`?

**Comment by mauritsvanrees** [comment]
The tests on 3.10 run now. Philip fixed it with https://github.com/collective/collective.exportimport/pull/172
