### ISSUE TITLE
Usage of json.dumps before deserialization @import

### ISSUE THREAD

**Issue by ThibautBorn** [collective/collective.exportimport#212]
Recently there was a change to deserializing when importing a new item. Now the item data is converted to a json string before the deserializer [using json.dumps](https://github.com/collective/collective.exportimport/blob/d4136c2ea360fee9d8e8d2ec42dc8f4eea31d92e/src/collective/exportimport/import_content.py#L430). This causes issues when deserializing decimal values however. So i was wondering why this change was made and if this change could be reverted?

**Comment by pbauer** [comment]
The reason is that not all deserializers support the `data=item` format and the default seems to be to use `json_body(self.request)` (e.g. https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/deserializer/site.py#L37).
So reverting this will break importing the site-root. I have not had to deal with decimals so far. Please tell me if you find another solution.

**Comment by avoinea** [comment]
I confirm this is a breaking one:

<pre>
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/collective/exportimport/import_content.py", line 409, in import_new_content
    new = self.handle_new_object(item, index, new)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/collective/exportimport/import_content.py", line 430, in handle_new_object
    self.request["BODY"] = json.dumps(item)
                           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Decimal is not JSON serializable
</pre>
