### ISSUE TITLE
KeyError: 'time' for history_item

### ISSUE THREAD

**Issue by zopyx** [collective/collective.exportimport#222]
Found during an export/import migration with v 1.9 on import:

```
WARNING:collective.exportimport.import_content:Didn't add Link http://nohost/magazine/archivio/2023/unopera-per-dar-voce-alle-storie-dellalluvione-che-ha-colpito-lemilia-romagna/condividi-la-tua-esperienza-racconta-per-esempio-in-che-modo-hai-dato-o-ricevuto-aiuto-cosa-ha-significato-per-te-come-ti-ha-fatto-sentire
Traceback (most recent call last):
  File "/Users/ajung/.buildout/eggs/collective.exportimport-1.9-py3.11.egg/collective/exportimport/import_content.py", line 409, in import_new_content
    new = self.handle_new_object(item, index, new)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ajung/.buildout/eggs/collective.exportimport-1.9-py3.11.egg/collective/exportimport/import_content.py", line 463, in handle_new_object
    self.import_workflow_history(new, item)
  File "/Users/ajung/.buildout/eggs/collective.exportimport-1.9-py3.11.egg/collective/exportimport/import_content.py", line 760, in import_workflow_history
    dateutil.parser.parse(history_item["time"])
                          ~~~~~~~~~~~~^^^^^^^^
KeyError: 'time'

```

**Comment by mauritsvanrees** [comment]
I see this as well, in version 1.10 (and current master).  Problem is when you have a workflow that does not have the `time` variable.  In my case, I have a workflow that does not have *any* variable, so `history_item` is only this:

    [{'review_state': 'private'}]

It is lacking a `time` key, so the import fails.
We inherited this project last year.  I guess there is no good reason for the missing variables.

Anyway, I am making a fix so the exportimport code does not trip on this.
