### ISSUE TITLE
Exporting relations sometimes fails with certain content objects that cannot be adapted (on crufty ZODBs)

### ISSUE THREAD

**Issue by Rudd-O** [collective/collective.exportimport#79]
Here is a diff that allows the program to continue.

```
diff --git a/src/collective/exportimport/export_other.py b/src/collective/exportimport/export_other.py
index 2cf8e33..201f7e7 100644
--- a/src/collective/exportimport/export_other.py
+++ b/src/collective/exportimport/export_other.py
@@ -117,7 +117,12 @@ class ExportRelations(BrowserView):
             if relation_catalog:
                 portal_catalog = getToolByName(self.context, "portal_catalog")
                 for rel in relation_catalog.findRelations():
-                    if rel.from_path and rel.to_path:
+                    try:
+                        rel_from_path_and_rel_to_path = rel.from_path and rel.to_path
+                    except ValueError:
+                        logger.exception("Cannot export relation %s, skipping", rel)
+                        continue
+                    if rel_from_path_and_rel_to_path:
                         from_brain = portal_catalog(
                             path=dict(query=rel.from_path, depth=0)
                         )
```

**Comment by Rudd-O** [comment]
Ah, forgot the traceback:

```
ERROR:collective.exportimport.export_other:Cannot export relation <z3c.relationfield.relation.RelationValue object at 0x7ca3245ad740 oid 0x15a56a in <Connection at 7ca3288bf070>>, skipping
Traceback (most recent call last):
  File "/home/user/optplone/buildout-cache/eggs/plone.app.relationfield-2.0.3-py3.8.egg/plone/app/relationfield/path.py", line 15, in path
    return '/'.join(obj.getPhysicalPath())
AttributeError: 'FormFolder' object has no attribute 'getPhysicalPath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/optplone/deployments/master/src/collective.exportimport/src/collective/exportimport/export_other.py", line 121, in get_all_references
    rel_from_path_and_rel_to_path = rel.from_path and rel.to_path
  File "/home/user/optplone/buildout-cache/eggs/z3c.relationfield-0.9.0-py3.8.egg/z3c/relationfield/relation.py", line 55, in to_path
    return _path(self.to_object)
  File "/home/user/optplone/buildout-cache/eggs/z3c.relationfield-0.9.0-py3.8.egg/z3c/relationfield/relation.py", line 138, in _path
    return object_path.path(obj)
  File "/home/user/optplone/buildout-cache/eggs/plone.app.relationfield-2.0.3-py3.8.egg/plone/app/relationfield/path.py", line 17, in path
    raise ValueError(obj)
ValueError: <persistent broken Products.PloneFormGen.content.form.FormFolder instance b'\x00\x00\x00\x00\x00\x15\xa5D'>
```

Obviously my site does not have PFG and cannot be installed even if I wanted to.

**Comment by pbauer** [comment]
You cannot export broken objects, you should exclude them in the export.

**Comment by Rudd-O** [comment]
I don't even know how to find the broken object much less reference it in the exclusion list :-(

**Comment by pbauer** [comment]
Since your issue is that you uninstalled `PloneFormGen` but still have items you could either delete theme, choose not export them or reinstall PloneFormGen. A exported `FormFolder` will not help you anyway in Plone 5. MIgrating to easyform is done within collective.easyform (works in Plone 4 or 5). It may be easier to recreate the forms by hand unless you have a lot of them. 

If you have more broken content you can try that in you `global_obj_hook`:

```
from ZODB.broken import PersistentBroken
if isinstance(obj, PersistentBroken):
    return
```

**Comment by mauritsvanrees** [comment]
He is not exporting PloneFormGen items. His problem is that there is a page which has a _relation_ to a broken PloneFormGen object. Our relation export code trips over this.

@Rudd-O Your inline diff seems okay at first glance. Can you make this into a pull request?

Alternative: install [`collective.relationhelpers`](https://github.com/collective/collective.relationhelpers) and use it to inspect and/or rebuild all relations.

**Comment by Rudd-O** [comment]
Relation helpers is already proving useful, and I am working around  the FormFolder broken object by using one of my workarounds.
