### ISSUE TITLE
AttributeError: modification_date_migrated while resetting dates

### ISSUE THREAD

**Issue by Rudd-O** [collective/collective.exportimport#82]
```
Traceback (most recent call last):
  File "/home/user/optplone/deployments/601a/parts/client1/bin/interpreter", line 294, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
  File "/home/user/optplone/deployments/601a/src/ruddocom.policy/src/ruddocom/policy/ctl/import_embedded.py", line 105, in <module>
    full_import(site, importpath, what)
  File "/home/user/optplone/deployments/601a/src/ruddocom.policy/src/ruddocom/policy/ctl/import_embedded.py", line 85, in full_import
    fixer()
  File "/home/user/optplone/deployments/601a/src/collective.exportimport/src/collective/exportimport/import_content.py", line 697, in __call__
    portal.ZopeFindAndApply(portal, search_sub=True, apply_func=reset_dates)
  File "/home/user/optplone/buildout-cache/eggs/Zope-5.3-py3.8.egg/OFS/FindSupport.py", line 171, in ZopeFindAndApply
    self.ZopeFindAndApply(ob, obj_ids, obj_metatypes,
  File "/home/user/optplone/buildout-cache/eggs/Zope-5.3-py3.8.egg/OFS/FindSupport.py", line 171, in ZopeFindAndApply
    self.ZopeFindAndApply(ob, obj_ids, obj_metatypes,
  File "/home/user/optplone/buildout-cache/eggs/Zope-5.3-py3.8.egg/OFS/FindSupport.py", line 165, in ZopeFindAndApply
    apply_func(ob, (apply_path + '/' + p))
  File "/home/user/optplone/deployments/601a/src/collective.exportimport/src/collective/exportimport/import_content.py", line 688, in reset_dates
    del obj.modification_date_migrated
AttributeError: modification_date_migrated
```

Why is this happening?

**Comment by Rudd-O** [comment]
Just spitballin' here:

```
        def reset_dates(obj, path):
            modified = getattr(obj, "modification_date_migrated", None)
            if modified and modified != obj.modification_date:
                obj.modification_date = modified
                del obj.modification_date_migrated
                obj.reindexObject(idxs=["modified"])
```

Technically under strict Python the `del` should have never been reached (wtf, right?).  I am thinking that perhaps the `modification_date_migrated` `getattr` is succeeding because of acquisition, and that is why the branch is taken, but the `del` fails.  Could that be?  If so, can the code be reformed to verify that, in fact, the modification date is coming from the object itself rather than from a parent?

**Comment by Rudd-O** [comment]
A partial diff I'm trying here:

```
@@ -685,13 +686,19 @@ class ResetModifiedAndCreatedDate(BrowserView):
             modified = getattr(obj, "modification_date_migrated", None)
             if modified and modified != obj.modification_date:
                 obj.modification_date = modified
-                del obj.modification_date_migrated
+                try:
+                    del obj.modification_date_migrated
+                except AttributeError:
+                    logger.warning("AttributeError while deleting modification date on %s", obj)
                 obj.reindexObject(idxs=["modified"])
 
             created = getattr(obj, "creation_date_migrated", None)
             if created and created != obj.creation_date:
                 obj.creation_date = created
-                del obj.creation_date_migrated
+                try:
+                    del obj.creation_date_migrated
+                except AttributeError:
+                    logger.warning("AttributeError while deleting creation date on %s", obj)
                 obj.reindexObject(idxs=["created"])
 
         portal.ZopeFindAndApply(portal, search_sub=True, apply_func=reset_dates)
```

**Comment by pbauer** [comment]
It might be a issue with aquisition. Try chaning it to:

`modified = getattr(obj.aq_base, "modification_date_migrated", None)` and `created = getattr(obj.aq_base, "creation_date_migrated", None)`

**Comment by Rudd-O** [comment]
I'll try that in a sec.

**Comment by Rudd-O** [comment]
Yup that worked!  Now you have a proper fix.  Thanks again, Phil!
