### ISSUE TITLE
Export from command line does not work

### ISSUE THREAD

**Issue by Rudd-O** [collective/collective.exportimport#92]
I hae a snippet of code that is supposed to export (and it works with all exports other than content), but when I try it _with content export_, I get a zero-bytes JSON file.  This snippet of code runs as an entry point of my `bin/client` program.

Does anyone know what the problem with the export is?

Code: https://gist.github.com/Rudd-O/f46154c80eb9937ec387e2b460ebbe8b

**Comment by Rudd-O** [comment]
Related: https://github.com/collective/collective.exportimport/pull/93

**Comment by Rudd-O** [comment]
Aha:

```
ERROR:collective.exportimport.export_content:Error exporting http://nohost/manuelamador.name/manuel-amador-lebenslauf
Traceback (most recent call last):
  File "/home/user/optplone/deployments/master/src/collective.exportimport/src/collective/exportimport/export_content.py", line 281, in export_content
    item = serializer()
  File "/home/user/optplone/buildout-cache/eggs/cp38/plone.restapi-6.15.0-py3.8.egg/plone/restapi/serializer/dxcontent.py", line 107, in __call__
    result["allow_discussion"] = getMultiAdapter(
  File "/home/user/optplone/buildout-cache/eggs/cp38/zope.component-4.6.2-py3.8.egg/zope/component/_api.py", line 104, in getMultiAdapter
    raise ComponentLookupError(objects, interface, name)
zope.interface.interfaces.ComponentLookupError: ((<Document at /manuelamador.name/manuel-amador-lebenslauf>, <HTTPRequest, URL=http://nohost>), <InterfaceClass zope.interface.Interface>, 'conversation_view')
```

All of my content objects raise `ComponentLookupError` when exported via the CLI.  This does not arise when exporting via the Web interface by point and click.

What gives?  Is my `REQUEST` object not valid or something?

**Comment by Rudd-O** [comment]
The snippet of code in `dxcontent.py` that specifically causes this:

```
        result["allow_discussion"] = getMultiAdapter(
            (self.context, self.request), name="conversation_view"
        ).enabled()
```

**Comment by Rudd-O** [comment]
By the way, the export from CLI problem happens in both Plone 5.x and Plone 6.

**Comment by Rudd-O** [comment]
Note that I have verified that the `configure.zcml` from `plone.app.discussion.browser` that registers the `conversation_view` is in fact loaded during the client script startup (I broke it intentionally and saw it fail to start).

**Comment by Rudd-O** [comment]
OK.

Using the CLI:

```
(<FolderishDocument at /manuelamador.name/manuel-amador-lebenslauf>, <HTTPRequest, URL=http://nohost>) [classImplements(?), directlyProvides(HTTPRequest, IDefaultBrowserLayer, IPathBlobsMarker, IMigrationMarker, IRawRichTextMarker, classImplements(HTTPRequest, IBrowserRequest, IAttributeAnnotatable))]
ERROR:collective.exportimport.export_content:Error exporting http://nohost/manuelamador.name/manuel-amador-lebenslauf
Traceback (most recent call last):
  File "/home/user/optplone/deployments/601a/src/collective.exportimport/src/collective/exportimport/export_content.py", line 280, in export_content
    item = serializer(include_items=False)
  File "/home/user/optplone/buildout-cache/eggs/cp38/plone.restapi-8.16.2-py3.8.egg/plone/restapi/serializer/dxcontent.py", line 150, in __call__
    folder_metadata = super().__call__(version=version)
  File "/home/user/optplone/buildout-cache/eggs/cp38/plone.restapi-8.16.2-py3.8.egg/plone/restapi/serializer/dxcontent.py", line 111, in __call__
    result["allow_discussion"] = getMultiAdapter(
  File "/home/user/optplone/buildout-cache/eggs/cp38/zope.component-4.6.2-py3.8.egg/zope/component/_api.py", line 104, in getMultiAdapter
    raise ComponentLookupError(objects, interface, name)
zope.interface.interfaces.ComponentLookupError: ((<FolderishDocument at /manuelamador.name/manuel-amador-lebenslauf>, <HTTPRequest, URL=http://nohost>), <InterfaceClass zope.interface.Interface>, 'conversation_view')
```

Using the Web UI:

```
(<FolderishDocument at /manuelamador.name/manuel-amador-lebenslauf>, <WSGIRequest, URL=http://127.0.1.4:8080/manuelamador.name/@@export_content>) [classImplements(?), directlyProvides(WSGIRequest, IPloneFormLayer, IDiscussionLayer, IThemingLayer, IBrowserLayer, IPloneAppContenttypesLayer, IThemeSpecific, collective.folderishtypes.dx.interfaces.IThemeSpecific, IManuelAmadorPolicyLayer, IDefaultBrowserLayer, IPathBlobsMarker, IMigrationMarker, IRawRichTextMarker)]
```

Analyzing differences now.

**Comment by Rudd-O** [comment]
Uh there's also no difference what request I use (tried both `makerequest` and a hack to use `WSGIRequest`).

**Comment by Rudd-O** [comment]
Could it be that the call to `setDefaultSkin` during Zope startup is not actually including the correct skins?

**Comment by Rudd-O** [comment]
Updated gist of code: https://gist.github.com/Rudd-O/4e657a90b8bc405de08d143221cee5ac  (the part where "content" is skipped should be removed).

To be run using `bin/client --no-request -c export_content.py site_id /path/to/export`.
